/**
 * Renders `db/seed-data.ts` from a map.
 *
 * Plain JS, not TypeScript, so that both sides can use it: the offline script
 * (`npm run db:export-seed`, which cannot import `.ts`) and the admin download
 * route in the running app. Two copies of this template would drift, and the
 * drift would only show up as a confusing diff months later, when somebody
 * exports from the droplet instead of from their laptop.
 *
 * @typedef {{
 *   name: string, x: number, y: number, kind: string, level: number,
 *   buffAtk: number, buffDef: number, buffHp: number,
 *   kingdom: number | null,
 *   amethystOverride: number | null,
 *   sapphireOverride: number | null,
 *   notes: string | null,
 * }} SeedFormatNode
 *
 * @typedef {{ aId: number, bId: number }} SeedFormatEdge
 *
 * @typedef {{
 *   id: number, number: number, name: string | null,
 *   color: string, sort: number,
 * }} SeedFormatKingdom
 */

/**
 * The line-up this map was surveyed with. Used when the database predates the
 * kingdoms table, so an export from an older file still produces a complete
 * seed rather than a map nobody can own.
 *
 * @type {SeedFormatKingdom[]}
 */
export const FALLBACK_KINGDOMS = [
  { id: 6, number: 6, name: null, color: "#3b82f6", sort: 0 },
  { id: 18, number: 18, name: null, color: "#ef4444", sort: 1 },
  { id: 26, number: 26, name: null, color: "#22c55e", sort: 2 },
  { id: 35, number: 35, name: null, color: "#eab308", sort: 3 },
];

const s = (v) => JSON.stringify(v);

/** Only the rare fields, and only when set — keeps a row on one line. */
function extra(n) {
  const parts = [];
  if (n.kingdom !== null && n.kingdom !== undefined) parts.push(`k: ${n.kingdom}`);
  if (n.amethystOverride !== null && n.amethystOverride !== undefined) {
    parts.push(`am: ${n.amethystOverride}`);
  }
  if (n.sapphireOverride !== null && n.sapphireOverride !== undefined) {
    parts.push(`sap: ${n.sapphireOverride}`);
  }
  if (n.notes) parts.push(`note: ${s(n.notes)}`);
  return parts.length ? `, { ${parts.join(", ")} }` : "";
}

/**
 * Build the file text.
 *
 * `nodes` must already be in the order the ids should be frozen in (id ASC);
 * edges are written as *index pairs into that array*, so the order is part of
 * the data, not a presentation choice.
 *
 * @param {{
 *   nodes: SeedFormatNode[],
 *   edges: SeedFormatEdge[],
 *   kingdoms?: SeedFormatKingdom[],
 *   ids?: number[],
 * }} map
 *  `ids[i]` is the database id of `nodes[i]`; needed to resolve edges. When
 *  omitted, edges are assumed to already carry array indices.
 * @returns {{ text: string, nodeCount: number, edgeCount: number, kingdomCount: number }}
 */
export function renderSeedFile({ nodes, edges, kingdoms, ids }) {
  const list = kingdoms && kingdoms.length > 0 ? kingdoms : FALLBACK_KINGDOMS;
  const index = new Map((ids ?? nodes.map((_, i) => i)).map((id, i) => [id, i]));

  const nodeLines = nodes.map(
    (n) =>
      `  [${s(n.name)}, ${n.x}, ${n.y}, ${s(n.kind)}, ${n.level}, ` +
      `${n.buffAtk}, ${n.buffDef}, ${n.buffHp}${extra(n)}],`,
  );

  // Ten pairs per line: 352 roads as one pair per line is unreadable noise.
  const edgeLines = [];
  const pairs = edges
    .filter((e) => index.has(e.aId) && index.has(e.bId))
    .map((e) => `[${index.get(e.aId)}, ${index.get(e.bId)}]`);
  for (let i = 0; i < pairs.length; i += 10) {
    edgeLines.push(`  ${pairs.slice(i, i + 10).join(", ")},`);
  }

  const kingdomLines = list.map(
    (k) =>
      `  { id: ${k.id}, number: ${k.number}, name: ${s(k.name)}, ` +
      `color: ${s(k.color)}, sort: ${k.sort} },`,
  );

  const text = `// Generated by \`npm run db:export-seed\` — do not edit by hand.
// Regenerate after changing the map through the UI.
import type { NodeKind } from "./schema";

/**
 * The map as it was surveyed in game: every object and every road.
 *
 * This is the *static* layer only. Who holds what, shields and check times are
 * live data and stay in the database — a fresh install starts with a fully
 * drawn, entirely unowned map.
 */

/** name, x, y, kind, level, atk%, def%, hp%, and the rare fields last. */
export type SeedNode = [
  name: string,
  x: number,
  y: number,
  kind: NodeKind,
  level: number,
  buffAtk: number,
  buffDef: number,
  buffHp: number,
  extra?: {
    /** Kingdom this object belongs to by design — bases carry it. */
    k?: number;
    am?: number;
    sap?: number;
    note?: string;
  },
];

export type SeedKingdom = {
  id: number;
  number: number;
  name: string | null;
  color: string;
  sort: number;
};

/**
 * Ids are stable internal slots and are what \`nodes.owner\` stores; the
 * in-game \`number\` beside them is a label an admin may change between events.
 * They start out equal, which is why ownership entered before kingdoms became
 * editable still reads correctly.
 */
export const SEED_KINGDOMS: SeedKingdom[] = [
${kingdomLines.join("\n")}
];

export const SEED_NODES: SeedNode[] = [
${nodeLines.join("\n")}
];

/** Roads, as index pairs into \`SEED_NODES\`. */
export const SEED_EDGES: [number, number][] = [
${edgeLines.join("\n")}
];
`;

  return {
    text,
    nodeCount: nodes.length,
    edgeCount: pairs.length,
    kingdomCount: list.length,
  };
}
