/**
 * Freeze the map that is in the database right now into `db/seed-data.ts`.
 *
 * The static layer — where the objects are, what type and level they are, what
 * they buff, and which roads connect them — is entered by hand once and then
 * never changes. Keeping it in code means a fresh database comes up already
 * filled in, and the file diffs like source when the map is corrected.
 *
 * Ownership, shields and check timestamps are deliberately *not* exported:
 * those change every hour and belong to the running database only.
 *
 *   node scripts/export-seed.mjs
 */
import Database from "better-sqlite3";
import { writeFileSync } from "node:fs";

const dbPath = process.env.SQLITE_PATH ?? "warzone.db";
const db = new Database(dbPath, { readonly: true });

const nodes = db.prepare("select * from nodes order by id").all();
const edges = db.prepare("select * from edges order by id").all();

/**
 * The line-up this map was surveyed with. Used when the database predates the
 * kingdoms table, so an export from an older file still produces a complete
 * seed rather than a map nobody can own.
 */
const FALLBACK_KINGDOMS = [
  { id: 6, number: 6, name: null, color: "#3b82f6", sort: 0 },
  { id: 18, number: 18, name: null, color: "#ef4444", sort: 1 },
  { id: 26, number: 26, name: null, color: "#22c55e", sort: 2 },
  { id: 35, number: 35, name: null, color: "#eab308", sort: 3 },
];

let kingdoms = [];
try {
  kingdoms = db.prepare("select * from kingdoms order by sort, id").all();
} catch {
  // Table not there yet.
}
if (kingdoms.length === 0) kingdoms = FALLBACK_KINGDOMS;

const index = new Map(nodes.map((n, i) => [n.id, i]));
const s = (v) => JSON.stringify(v);

/** Only the rare fields, and only when set — keeps a row on one line. */
function extra(n) {
  const parts = [];
  if (n.kingdom !== null) parts.push(`k: ${n.kingdom}`);
  if (n.amethyst_override !== null) parts.push(`am: ${n.amethyst_override}`);
  if (n.sapphire_override !== null) parts.push(`sap: ${n.sapphire_override}`);
  if (n.notes) parts.push(`note: ${s(n.notes)}`);
  return parts.length ? `, { ${parts.join(", ")} }` : "";
}

const nodeLines = nodes.map(
  (n) =>
    `  [${s(n.name)}, ${n.x}, ${n.y}, ${s(n.kind)}, ${n.level}, ` +
    `${n.buff_atk}, ${n.buff_def}, ${n.buff_hp}${extra(n)}],`,
);

// Ten pairs per line: 352 roads as one pair per line is unreadable noise.
const edgeLines = [];
const pairs = edges
  .filter((e) => index.has(e.a_id) && index.has(e.b_id))
  .map((e) => `[${index.get(e.a_id)}, ${index.get(e.b_id)}]`);
for (let i = 0; i < pairs.length; i += 10) {
  edgeLines.push(`  ${pairs.slice(i, i + 10).join(", ")},`);
}

const kingdomLines = kingdoms.map(
  (k) =>
    `  { id: ${k.id}, number: ${k.number}, name: ${s(k.name)}, ` +
    `color: ${s(k.color)}, sort: ${k.sort} },`,
);

const out = `// Generated by \`npm run db:export-seed\` — do not edit by hand.
// Regenerate after changing the map through the UI.
import type { NodeKind } from "./schema";

/**
 * The map as it was surveyed in game: every object and every road.
 *
 * This is the *static* layer only. Who holds what, shields and check times are
 * live data and stay in the database — a fresh install starts with a fully
 * drawn, entirely unowned map.
 */

/** name, x, y, kind, level, atk%, def%, hp%, and the rare fields last. */
export type SeedNode = [
  name: string,
  x: number,
  y: number,
  kind: NodeKind,
  level: number,
  buffAtk: number,
  buffDef: number,
  buffHp: number,
  extra?: {
    /** Kingdom this object belongs to by design — bases carry it. */
    k?: number;
    am?: number;
    sap?: number;
    note?: string;
  },
];

export type SeedKingdom = {
  id: number;
  number: number;
  name: string | null;
  color: string;
  sort: number;
};

/**
 * Ids are stable internal slots and are what \`nodes.owner\` stores; the
 * in-game \`number\` beside them is a label an admin may change between events.
 * They start out equal, which is why ownership entered before kingdoms became
 * editable still reads correctly.
 */
export const SEED_KINGDOMS: SeedKingdom[] = [
${kingdomLines.join("\n")}
];

export const SEED_NODES: SeedNode[] = [
${nodeLines.join("\n")}
];

/** Roads, as index pairs into \`SEED_NODES\`. */
export const SEED_EDGES: [number, number][] = [
${edgeLines.join("\n")}
];
`;

writeFileSync("db/seed-data.ts", out);
console.log(
  `db/seed-data.ts: ${nodes.length} nodes, ${pairs.length} edges, ${kingdoms.length} kingdoms`,
);
